### ISSUE TITLE
Nas synology

### ISSUE THREAD

**Issue by Michmouth** [marklagendijk/node-toogoodtogo-watcher#106]
Hello.
Already I would like to thank the creator of this tool! It works perfectly on my pc.
I am aiming to buy a synology ds220 + nas. I understood that the tool could work with it. If I understood correctly, you no longer need a computer to make it work?
Is it possible to have explanations on the installation (step by step) of toogoodtogo watcher on the nas?
Thanks a lot for your help.

**Comment by marklagendijk** [comment]
I believe you can use Docker on Synology. So that is probably your best bet.
