### ISSUE TITLE
v2/loginByEmail endpoint doesn't seem to work anymore

### ISSUE THREAD

**Issue by fejiso** [marklagendijk/node-toogoodtogo-watcher#112]
Hi. As per the title:

```
POST https://apptoogoodtogo.com/api/auth/v2/loginByEmail
{
    "device_type": "UNKNOWN",
    "email": "Email of your TooGoodToGo account.",
    "password": "Password of your TooGoodToGo account."
}
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/home/node/app/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

From my sniffing session, the endpoint has been replaced by v3/authByEmail (not loginByEmail!) which doesn't use password anymore (even though the app asks for it), but it requires the user to click a link from the verification email (or input the code provided in the app).

**Comment by MaxWinterstein** [comment]
> (even though the app asks for it)
No password request for me here

Did you get further with the endpoints? Is the code / link sent towards the server again? 

( Coming from the python side: https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/112 )

**Comment by fejiso** [comment]
From what I've seen the app polls until the link has been clicked (auth/v3/authByRequestPollingId) until it gets a response with the access_token.

Haven't tested the code approach, not sure it's even worth implementing either for an end user.

**Comment by MaxWinterstein** [comment]
well, seems I need to tell wifey there will be no more cheap sushi for her 🤕 

Would love to see some full walkthrough for this!  
Might need to fetch the mail programmatically I guess...

**Comment by danickfort** [comment]
> From what I've seen the app polls until the link has been clicked (auth/v3/authByRequestPollingId); once it happens it gets a response with the access_token.
> 
> Haven't tested the code approach, not sure it's even worth implementing either for an end user.

It seems like `auth/v3/authByRequestPollingId` does respond with a payload that is similar to the old `loginByEmail` endpoint, once the link in the email has been visited. Also, when visiting the verification link in the email, it looks like it's doing some ajax/websocket stuff, so automating the process via mail fetcher + a simple GET HTTP request probably won't work.

Also, I quickly tried using the `access_token` that I've gotten from the response on the `item/v7` endpoint, but I still get a 403 on it 🙁

**Comment by D-VR** [comment]
> > From what I've seen the app polls until the link has been clicked (auth/v3/authByRequestPollingId); once it happens it gets a response with the access_token.
> 
> > 
> 
> > Haven't tested the code approach, not sure it's even worth implementing either for an end user.
> 
> 
> 
> It seems like `auth/v3/authByRequestPollingId` does respond with a payload that is similar to the old `loginByEmail` endpoint, once the link in the email has been visited. Also, when visiting the verification link in the email, it looks like it's doing some ajax/websocket stuff, so automating the process via mail fetcher + a simple GET HTTP request probably won't work.
> 
> 
> 
> Also, I quickly tried using the `access_token` that I've gotten from the response on the `item/v7` endpoint, but I still get a 403 on it 🙁 


For me the Login Email also includes a Code that can be used instead of the link.
It should be possible to automate it with that.

But I think for most people running it locally, having no automation might be easier to set up.
The access token should last for a while.

**Comment by marklagendijk** [comment]
The first approach I would try would be to mimic the approach from the app as much as possible. 
1. When the program is started and no session exist yet, start the login procedure by calling the API. 
2. The program starts polling `auth/v3/authByRequestPollingId`
3. The API sends the user an email.
4. The user clicks the link in the email.
5. The program receives the session and continues.

Things like automating accessing emails and scraping a CSRF token from a HTML form can be done if necessary, but I would avoid them, if possible.

**Comment by MaxWinterstein** [comment]
Okay, had some little play with `mitmproxy`:

![image](https://user-images.githubusercontent.com/5927148/141017676-3d3ad215-8b0c-4ca6-8c59-e3852d4ec1e7.png)

From what I can tell:

1. the First request goes to `https://apptoogoodtogo.com/api/auth/v3/authByEmail` and is responded with some `polling_id`. 
2. Next responses go towards `https://apptoogoodtogo.com/api/auth/v3/authByRequestPollingId` containing (besides more) the `request_polling_id`. 
3. as long as the link is not clicked (tried on my workstation) the request is responded with `202`
4. after the link has been clicked it is responded with `200` and contains access token and a `access_token_ttl_seconds` of 172800s / 2days.

So, throwing that knowledge against some jupyter-notebook (sorry nodejs guys):

![image](https://user-images.githubusercontent.com/5927148/141021421-3da1e328-908e-4f04-be34-38b285fa0896.png)
Note: `/authByEmail` quickly blocks with `429 too many requests`, take care

Never took a deeper dive, but i guess the gained `access_token` is what we need to be happy.

So a version that requires the user to open his mail and hit the button should not be that big issue I guess?

**Comment by MaxWinterstein** [comment]
coffee break update: 

Using the PIN method is quite similar. 

- After requesting the login email it starts pulling at `v3/authByRequestPollingId`
- When the PIN is entered a `POST` is sent to `v3/authByRequestPin` with the pin and some more data
- response is similar to the `200` version of `v3/authByRequestPollingId`
![image](https://user-images.githubusercontent.com/5927148/141089785-b37a1c5b-d900-40fe-9aef-3b688be68875.png)

Might have a little try to get this into the python version, to have a full walkthrough. 

Thinking of using some trash email that allows API usage (e.g. https://temp-mail.org/ ). Adding some forwarding rule towards them fetching the code is candy.

**Comment by RobertPegu** [comment]
That is weird, I don't have this kind of errors. I have 403 but looks like I can login successfully with email and password (see #113 )

**Comment by rayhvh** [comment]
> well, seems I need to tell wifey there will be no more cheap sushi for her 🤕
> 
> Would love to see some full walkthrough for this! Might need to fetch the mail programmatically I guess...

It's been day 2. I think she is starting to notice the empty fridge. Im tooscaredtotell.

Thanks for helping this getting up again. If I can assist in any way.

**Comment by andrzejpodgorny** [comment]
And is the bot working for you? Could you explain more?

**Comment by MaxWinterstein** [comment]
> tooscaredtotell

took a few seconds, but hit right in the laugh box

---

As time is short, I was able to have a little more play an that one. A few things I found:

They use `datadome` as bot protection. It is a SaaS solution to prevent people like us to do this like we do. And they are the reason for those `captcha-delivery.com` stuff.  

(If there is any toogoodtogo employee here: pls don't sue me, we do this for fun and to make our wifes happy and not to hurt anybody. We even pay like regular customers. Don't ban/sue us pls 🥺 .)

Trying to get fav pulled with the new token always hit me with those captcha requests. 
While looking at the traffic I saw that the app passes always place some cookie in the header, with I ignored at first.  
But, when resuing the cookie from the successful `api/auth/v3/authByRequestPollingId` post, I got a perfect response!

![](https://c.tenor.com/XMVz4JeILUMAAAAM/ladies-and-gentleman-we-got-him.gif)

With that said, I am not sure how their protection works in detail. I tried aggressively to fetch 100 times and now ran against the captcha even when trying to login freshly. App also enforced me to click on traffic lights...

Proof:

![image](https://user-images.githubusercontent.com/5927148/141381926-d90532a7-f87a-49da-9838-77119085ea73.png)

I think we now have all information needed to fix this thing. As I still have no time and effort to learn node-js, I might jump over to the python one and try to get it working.

**Comment by MaxWinterstein** [comment]
> tooscaredtotell

took a few seconds, but hit right in the laugh box

---

As time is short, I was able to have a little more play an that one. A few things I found:

They use `datadome` as bot protection. It is a SaaS solution to prevent people like us to do this like we do. And they are the reason for those `captcha-delivery.com` stuff.  

(If there is any toogoodtogo employee here: pls don't sue me, we do this for fun and to make our wifes happy and not to hurt anybody. We even pay like regular customers. Don't ban/sue us pls 🥺 .)

Trying to get fav pulled with the new token always hit me with those captcha requests. 
While looking at the traffic I saw that the app passes always place some cookie in the header, with I ignored at first.  
But, when resuing the cookie from the successful `api/auth/v3/authByRequestPollingId` post, I got a perfect response!

![](https://c.tenor.com/XMVz4JeILUMAAAAM/ladies-and-gentleman-we-got-him.gif)

With that said, I am not sure how their protection works in detail. I tried aggressively to fetch 100 times and now ran against the captcha even when trying to login freshly. App also enforced me to click on traffic lights...

Proof:

![image](https://user-images.githubusercontent.com/5927148/141382802-fdf46c26-d8f6-48c7-908a-11fc9054e4b7.png)

I think we now have all information needed to fix this thing. As I still have no time and effort to learn node-js, I might jump over to the python one and try to get it working.

**Comment by unixfox** [comment]
Funny enough, but just adding `"accept-encoding": "gzip"` after this line fixed the issue: https://github.com/marklagendijk/node-toogoodtogo-watcher/blob/master/lib/api.js#L10! :laughing:

**Comment by TanguyOrtegat** [comment]
> > tooscaredtotell
> 
> took a few seconds, but hit right in the laugh box
> 
> As time is short, I was able to have a little more play an that one. A few things I found:
> 
> They use `datadome` as bot protection. It is a SaaS solution to prevent people like us to do this like we do. And they are the reason for those `captcha-delivery.com` stuff.
> 
> (If there is any toogoodtogo employee here: pls don't sue me, we do this for fun and to make our wifes happy and not to hurt anybody. We even pay like regular customers. Don't ban/sue us pls 🥺 .)
> 
> Trying to get fav pulled with the new token always hit me with those captcha requests. While looking at the traffic I saw that the app passes always place some cookie in the header, with I ignored at first. But, when resuing the cookie from the successful `api/auth/v3/authByRequestPollingId` post, I got a perfect response!
> 
> ![](https://camo.githubusercontent.com/4d42d474b77a299e15365f2e9a08b24bf39170188559035618440c758eb16b7c/68747470733a2f2f632e74656e6f722e636f6d2f584d567a344a65494c554d414141414d2f6c61646965732d616e642d67656e746c656d616e2d77652d676f742d68696d2e676966)
> 
> With that said, I am not sure how their protection works in detail. I tried aggressively to fetch 100 times and now ran against the captcha even when trying to login freshly. App also enforced me to click on traffic lights...
> 
> Proof:
> 
> ![image](https://user-images.githubusercontent.com/5927148/141382802-fdf46c26-d8f6-48c7-908a-11fc9054e4b7.png)
> 
> I think we now have all information needed to fix this thing. As I still have no time and effort to learn node-js, I might jump over to the python one and try to get it working.

I use this repo as bot in python: https://github.com/maxux/toogoodtogo-watcher
but same issue for v2/loginByEmail, but maybe yu can fix it over there ?

**Comment by lampje25** [comment]
same problems here.
this morning it still worked.
Not anymore unfortunately.

Traceback (most recent call last):
File "C:\Python39\tgtg_get_tokens.py", line 15, in
client.get_items()
File "C:\Python39\tgtg_init_.py", line 151, in get_items
self.login()
File "C:\Python39\tgtg_init_.py", line 130, in login
raise TgtgLoginError(response.status_code, response.content)
tgtg.exceptions.TgtgLoginError: (404, b'')
