### ISSUE TITLE
always Error during request

### ISSUE THREAD

**Issue by jfadeuilhe** [marklagendijk/node-toogoodtogo-watcher#119]
always
Error during request:
POST https://apptoogoodtogo.com/api/auth/v2/loginByEmail
{
    "device_type": "IOS",
    "email": "xxxx",
    "password": "xxxx"
}

HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/usr/local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

I have installed a VPN to change IP, it does not change anything

I do not know what else to try

**Comment by alice17** [comment]
I have the same problem since yesterday evening

**Comment by goegol** [comment]
I have the same issue with python code, looks like tgtg change stuff?

**Comment by andrzejpodgorny** [comment]
Yep, i guess that's over :)

**Comment by TommyLR** [comment]
@andrzejpodgorny what do you mean that's over?

**Comment by tuffo19** [comment]
an update is required, since it is now asking a new kind of token

**Comment by sbx59** [comment]
Hello, it would seem that if we set a timer: 60 seconds to 80 seconds, the application no longer asks for this identification (you must of course quit the application a few days before!)

**Comment by Slothoncrack** [comment]
So how can we solve this problem? Any solution yet?
And @sbx59 what do you mean with timer? Something in the config.json to set?

**Comment by sbx59** [comment]
instead of updating every second or 2 second, it would be necessary to update 60 or 80 seconds less often at random.

**Comment by Slothoncrack** [comment]
Okay, thanks.
For the login, we need the tokens, apparently we can retrieve them using this fork: https://github.com/Dielee/tgtg-python but I cant quite figure it out... I can get the mail sent but dont know where/how to retrieve the tokens (print (client.access_token) does nothing for me) Can anyone explain to a layman like me?

**Comment by sbx59** [comment]
not necessarily need a token. with an IP, which does not know connected to TGTG that did not ask me to confirm.

**Comment by Ismaouste** [comment]
I'm experiencing the same issue, anyone found a workaround yet ? Is the  Dielee/tgtg-python the only functioning fork ?

**Comment by goegol** [comment]
Jup, yesterday there is a new version of the tgtg libary released

**Comment by c0lumb0** [comment]
Ok, thx. Just the lib-folder or anything else?
Are there any other steps needed? Or is this documented somewhere...can't find it right now.

**Comment by c0lumb0** [comment]
Ok, just seen that you're referring to

https://github.com/ahivert/tgtg-python

which is based on python, but since this watcher was based on nodejs I would not know how to convert this

**Comment by marklagendijk** [comment]
Please retry with the latest version (3.8.0) and login with either via the command line or via the Telegram bot.
