### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by omix12** [marklagendijk/node-toogoodtogo-watcher#121]
Hello,

I've got the following error:

```
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/usr/local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Could you help? All was working fine till today evening :(

**Comment by sembsa** [comment]
I have this same:

Error during request:
POST https://apptoogoodtogo.com/api/auth/v2/loginByEmail
{
    "device_type": "IOS",
    "email": "xxxxxxx",
    "password": "xxxxxxxx"
}
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/home/node/app/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by navimondo** [comment]
Exactly same here when trying to login this morning.
-------------------------------------
POST https://apptoogoodtogo.com/api/auth/v2/loginByEmail
HTTPError: Response code 403 (Forbidden)
-------------------------------------
Br,

Kris

**Comment by DzianisMakeichyk** [comment]
looks like refresh_token is baned 🤔

**Comment by doublebyte1** [comment]
The login by email was discontinued: now an 2FA, with email is in place. Once you confirm the email, a token is generated. You can use that in the get item request.

**Comment by kequach** [comment]
> looks like refresh_token is baned 🤔

Does this mean there is currently no way to use this tool?

**Comment by koff75** [comment]
That's normal, they changed their authent. method... they send you an unique digit code as password...
I tried to intercept the post request but they're using SSL pinning on their android app :/ it's gonna take more time to bypass...

**Comment by PileOfJunkMail** [comment]
I got it working again using the changes to api.js below. After making these changes, I used authByEmail and authPoll by hand to get a new refresh token. (I don't know how to properly integrate this in the rest of the code.) I did this four days ago, and I haven't had issues since.

```--- a/lib/api.js
+++ b/lib/api.js
@@ -8,7 +8,7 @@ const api = got.extend({
     "User-Agent":
       "TooGoodToGo/21.9.0 (813) (iPhone/iPhone 7 (GSM); iOS 15.1; Scale/2.00)",
     "Content-Type": "application/json",
-    Accept: "application/json",
+    "Accept": "",
     "Accept-Language": "en-US",
     "Accept-Encoding": "gzip",
   }),
@@ -17,10 +17,38 @@ const api = got.extend({
 });
 
 module.exports = {
+  authByEmail,
+  authPoll,
   login,
   listFavoriteBusinesses,
 };
 
+function authByEmail() {
+  const credentials = config.get("api.credentials");
+
+  return api
+    .post("auth/v3/authByEmail", {
+      json: {
+        device_type: "ANDROID",
+        email: credentials.email,
+      },
+    });
+}
+
+function authPoll(polling_id) {
+  const credentials = config.get("api.credentials");
+
+  return api
+    .post("auth/v3/authByRequestPollingId", {
+      json: {
+        device_type: "ANDROID",
+        email: credentials.email,
+        request_polling_id: polling_id,
+      },
+    })
+    .then(createSession);
+}
+
 function login() { 
  const session = getSession();
   return session.refreshToken ? refreshToken() : loginByEmail();
@@ -44,7 +72,7 @@ function refreshToken() {
   const session = getSession();
 
   return api
-    .post("auth/v2/token/refresh", {
+    .post("auth/v3/token/refresh", {
       json: {
         refresh_token: session.refreshToken,
       },
```

**Comment by DzianisMakeichyk** [comment]
@PileOfJunkMail can you make a PR with this changes here?

**Comment by c0lumb0** [comment]
Still getting the error as before after changing api.js accordingly. Is it working for anybody else?

**Comment by DzianisMakeichyk** [comment]
Works for me

**Comment by c0lumb0** [comment]
Hm..must have missed something, since I updated to the latest version and added the changes in api.js...Is there any other change needed that has popped up in the meantime?

**Comment by DzianisMakeichyk** [comment]
PR https://github.com/marklagendijk/node-toogoodtogo-watcher/pull/122 with changes :)

**Comment by KSuondProject** [comment]
Hi! How I can implement this correction in my system? :)
Thank you.

> I got it working again using the changes to api.js below. After making these changes, I used authByEmail and authPoll by hand to get a new refresh token. (I don't know how to properly integrate this in the rest of the code.) I did this four days ago, and I haven't had issues since.
> 
> ```
> +++ b/lib/api.js
> @@ -8,7 +8,7 @@ const api = got.extend({
>      "User-Agent":
>        "TooGoodToGo/21.9.0 (813) (iPhone/iPhone 7 (GSM); iOS 15.1; Scale/2.00)",
>      "Content-Type": "application/json",
> -    Accept: "application/json",
> +    "Accept": "",
>      "Accept-Language": "en-US",
>      "Accept-Encoding": "gzip",
>    }),
> @@ -17,10 +17,38 @@ const api = got.extend({
>  });
>  
>  module.exports = {
> +  authByEmail,
> +  authPoll,
>    login,
>    listFavoriteBusinesses,
>  };
>  
> +function authByEmail() {
> +  const credentials = config.get("api.credentials");
> +
> +  return api
> +    .post("auth/v3/authByEmail", {
> +      json: {
> +        device_type: "ANDROID",
> +        email: credentials.email,
> +      },
> +    });
> +}
> +
> +function authPoll(polling_id) {
> +  const credentials = config.get("api.credentials");
> +
> +  return api
> +    .post("auth/v3/authByRequestPollingId", {
> +      json: {
> +        device_type: "ANDROID",
> +        email: credentials.email,
> +        request_polling_id: polling_id,
> +      },
> +    })
> +    .then(createSession);
> +}
> +
>  function login() { 
>   const session = getSession();
>    return session.refreshToken ? refreshToken() : loginByEmail();
> @@ -44,7 +72,7 @@ function refreshToken() {
>    const session = getSession();
>  
>    return api
> -    .post("auth/v2/token/refresh", {
> +    .post("auth/v3/token/refresh", {
>        json: {
>          refresh_token: session.refreshToken,
>        },
> ```

**Comment by c0lumb0** [comment]
> PR #122 with changes :)

That's what I did :)
Changing lib/api.js according to PR #122 but still getting

Error during request:
POST https://apptoogoodtogo.com/api/auth/v3/loginByEmail
{
    "device_type": "IOS",
    "email": "xxxxx",
    "password": "xxxxx#"
}

HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by c0lumb0** [comment]
> You have to implement the caller function : "function authPoll(polling_id)" somewhere else. In my sense, that's not in the present commit...

Where would you set it in the current api.js?

**Comment by c0lumb0** [comment]
Just found out, thx to this comment

https://github.com/marklagendijk/node-toogoodtogo-watcher/pull/122#pullrequestreview-825312363

that PR #122 is just working when you add a valid refresh token from past versions of the application, if you used it before.

**Comment by AntoineCardon** [comment]
> 

Hey, Can you be more specific about the way to "refresh manually token" please ? :)

**Comment by c0lumb0** [comment]
> > 
> 
> Hey, Can you be more specific about the way to "refresh manually token" please ? :)

In the config file of previous versions of this application, there was a token value in the

"session": {}

line. I just added this again.

**Comment by PileOfJunkMail** [comment]
Hi all. Sorry for the confusion. That patch was not finished code, I posted it in the hopes that somebody else would finish it. I know nothing about NodeJS :) But here's a PR that's clumsy but complete: https://github.com/marklagendijk/node-toogoodtogo-watcher/pull/123

If you still have an old refresh token, it might work immediately. Otherwise you have to request a login email with `node index.js login` and follow the instructions.

Note, if you have a custom User-Agent header configured in your config (perhaps as a past work-around), you probably need to remove it again.

**Comment by marklagendijk** [comment]
Please retry with the latest version (3.8.0) and login with either via the command line or via the Telegram bot.
