### ISSUE TITLE
thanks it work but one question

### ISSUE THREAD

**Issue by laurentdu56** [marklagendijk/node-toogoodtogo-watcher#142]
hi thanks a lot it work with telegram i received the new products available but only when the computer is open. is it possible to still the watch working all the time (even with computer/watch windows off) ?
have a nice day :)

**Comment by schklom** [comment]
It is a software, it needs to run somewhere.

What you can do is either get a server (old computer/raspberry pi/industrial server/etc) or rent one online (like Linode/etc) or use a free one online (Oracle Cloud/Amazon Web Services/Google Cloud/etc), and let this software run there.

A good way to get started is to buy a raspberry pi zero (around 20$ in total), let it be continuously plugged to an electrical outlet, and install node-toogoodtogo-watcher there.
The power draw will ridiculously small, like 2W, which would cost you around 1$/year in electricity.

**Comment by laurentdu56** [comment]
thanks for your answer. 
i will reinstall on a server. i think i don't understand someting regarding nodejs prompt command to run the soft.
i put "watch" to run it. if the windows is closed the soft dont run anymore. 
if i reinstall it online how could i still the soft run?

thanks :)
laurent.

**Comment by laurentdu56** [comment]
hello,

thanks a lot for these elements
i have to study this :)
