### ISSUE TITLE
HTTPError: Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by GrMoney93** [marklagendijk/node-toogoodtogo-watcher#148]
Starting this afternoon I got my first Captcha request within the toogoodtogo app itself.

At the exact same time the toogoodtogo-watcher started receiving 403 errors. I have attempted to reinstall and login but upon logging in I only get the following error message:

```
Something went wrong: HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1647539004170,
    socket: 1647539004173,
    lookup: 1647539004199,
    connect: 1647539004219,
    secureConnect: 1647539004258,
    upload: 1647539004259,
    response: 1647539004320,
    end: 1647539004329,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 26,
      tcp: 20,
      tls: 39,
      request: 1,
      firstByte: 61,
      download: 9,
      total: 159
    }
  }
}
```

This is my config file:

```
{
	"api": {
		"credentials": {
			"email": "xxxxxxx@gmail.com"
		},
		"session": {},
		"deviceType": "IOS",
		"headers": {},
		"pollingIntervalInMs": 30000,
		"authenticationIntervalInMS": 3600000
	},
	"notifications": {
		"console": {
			"enabled": false,
			"clear": true
		},
		"desktop": {
			"enabled": true
		},
		"telegram": {
			"enabled": false,
			"botToken": "See README",
			"chats": []
		},
		"ifttt": {
			"enabled": false,
			"webhookKey": "see README",
			"webhookEvents": [
				"see README"
			]
		},
		"gotify": {
			"enabled": false,
			"url": "http://push.example.com",
			"apptoken": "token",
			"priority": 5
		}
	},
	"messageFilter": {
		"showUnchanged": false,
		"showDecrease": false,
		"showDecreaseToZero": false,
		"showIncrease": false,
		"showIncreaseFromZero": true
	}
}
```

This was the original error message:

```
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\got\dist\source\as-promise\index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error during request:
POST https://apptoogoodtogo.com/api/item/v7/
{
    "favorites_only": true,
    "origin": {
        "latitude": xx.xxxxxx,
        "longitude": xx.xxxxxxx
    },
    "radius": 200,
    "user_id": "xxxxxxxxxx"
}
```

**Comment by GrMoney93** [comment]
Update: As of this morning I am able to log in again.

I will run the script for a couple of days, to see if the previous error re-occurs, and then I will update this thread.

**Comment by Nomercyme** [comment]
HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (C:\Users\k\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error during request:
POST https://apptoogoodtogo.com/api/item/v7/

I have been getting this error, could this be some type of captcha thing?

**Comment by laurentdu56** [comment]
i've got the same problem :(

**Comment by fxhuhn** [comment]
for me too

`HTTPError: Response code 403 (Forbidden)`

**Comment by GrMoney93** [comment]
Error has now reoccured on post:

```
Error during request:
POST https://apptoogoodtogo.com/api/item/v7/
{
    "favorites_only": true,
    "origin": {
        "latitude": xx.xxxxxx,
        "longitude": xx.xxxxxx
    },
    "radius": 200,
    "user_id": "xxxxxxxx"
}

HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\toogoodtogo-watcher\node_modules\got\dist\source\as-promise\index.js:117:42)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by basti1499** [comment]
Same for me. The script runs well for a bunch of minutes and then puts out the 403 error for each request.

Feels like TGTG is giving out cooldowns for too many requests :(

**Comment by zirconiium** [comment]
yeah you now need to provide the "cookie" in the request, might send a PR if the owner don't resolve it in the following days

**Comment by c0lumb0** [comment]
Same issue here too.
Are there already some ideas for a PR?

**Comment by jozefszymala** [comment]
> yeah you now need to provide the "cookie" in the request, might send a PR if the owner don't resolve it in the following days

@zirconiium could you create PR? or tell which cookie need to be set?

**Comment by user902835098** [comment]
I think I've fixed it, not sure if it's the best solution and if it works on all devices... but has been running without issues for the past hour. Cookies need to be enabled for the requests to work again.

You need to install the `tough-cookie` and `http-cookie-agent` module.

api.js edits:
`const _ = require("lodash");
const got = require("got");
const { config } = require("./config");
**const { CookieJar } = require("tough-cookie");
const { HttpCookieAgent, HttpsCookieAgent } = require('http-cookie-agent');**

**const jar = new CookieJar();**

const api = got.extend({
**agent: {
    http: new HttpCookieAgent({ jar }),
    https: new HttpsCookieAgent({ jar }),
  },**
.... headers etc. ....
`

**Comment by basti1499** [comment]
> I think I've fixed it, not sure if it's the best solution and if it works on all devices... but has been running (on raspberry) without issues for the past hour. Cookies need to be enabled for the requests to work again.
> 
>[...]

This seems to work for me as well.
Thanks for the quick and easy fix @user902835098 😄

**Comment by c0lumb0** [comment]
Same here as well, seems to work just fine again. Big thx!

**Comment by marklagendijk** [comment]
Thanks for the fix. I'm too lazy / busy to look into things myself. However, I usually do (eventually) find the time to apply stuff other people figured out.
Fix has been released.

**Comment by gielk** [comment]
It is not fixed for me.
