### ISSUE TITLE
Error with refreshing Token

### ISSUE THREAD

**Issue by DaRabus** [marklagendijk/node-toogoodtogo-watcher#15]
Hey, I hope there is an easy solution, I think The App banned the IP or the Agent and cant refresh the token anymore.

Tried to change my passwort and will try another Account now, but maybe something to be considered.
EDIT: Tried another Account, same Error.
EDIT: Reset Settings now it works again^^

Worked quite well for a while but now after 2 weeeks it stopped working.

![grafik](https://user-images.githubusercontent.com/44967066/83020581-f6ebb580-a028-11ea-8145-abbce16867c7.png)

**Comment by marklagendijk** [comment]
The refresh token is saved in the settings file. This refresh token is used to request a new access token. So for some reason you ended up with an invalid refresh token, and resetting the settings file fixed that.
