### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by jfadeuilhe** [marklagendijk/node-toogoodtogo-watcher#150]
Hello,

Error during request:
POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
{
    "refresh_token": "e30.eyJzd .../... JmFI3qo"
}

HTTPError: Response code 403 (Forbidden)
    at Request.&lt;anonymous&gt; (/usr/local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Thanks for the quick reaction, but v3.9.0 doesn't work on my Synology   :-(

I installed the both components:
npm install -g tough-cookie
npm install -g http-cookie-agent

Do I have to do anything else ?

Good Sunday !

**Comment by wouterman** [comment]
Hi,

According to [this ](https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/148) issue, closed yesterday, this has just been fixed in the new release. ([V3.9.0](https://github.com/marklagendijk/node-toogoodtogo-watcher/releases/tag/v3.9.0)) :)

**Comment by jfadeuilhe** [comment]
Yes, but as stated it does not work for me on Synology

I installed the components indicated in this issue, but do I have to do anything else?

**Comment by EsEnZeT** [comment]
Same here, 403, also actual source looks a bit different than proposed change, not sure if that matters 

https://github.com/marklagendijk/node-toogoodtogo-watcher/blob/master/lib/api.js
https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/148#issuecomment-1073048888

**Comment by mafrasi2** [comment]
I had the same issue yesterday. I assume it was because my IP was banned after days of invalid requests, because it works with a VPN now.

@jfadeuilhe you have to apply [this entire patch](https://github.com/marklagendijk/node-toogoodtogo-watcher/commit/50e72668c938a4d013d131f46a2514b88799ab4b).

**Comment by jfadeuilhe** [comment]
Maybe banned, indeed.
I suspend my processes and I will try to restart it later.

on the other hand I don't know what to do with "apply this entire patch.", I installed v3.9.0, it doesn't include everything?

**Comment by mafrasi2** [comment]
> on the other hand I don't know what to do with "apply this entire patch.", I installed v3.9.0, it doesn't include everything?

Ah, I misunderstood. You're right, that should be enough.

**Comment by jfadeuilhe** [comment]
Hello 

I tried to login this morning, without success :

Something went wrong: HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/usr/local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1647845229734,
    socket: 1647845229737,
    lookup: 1647845229763,
    connect: 1647845229776,
    secureConnect: 1647845229791,
    upload: 1647845229792,
    response: 1647845229828,
    end: 1647845229836,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 26,
      tcp: 13,
      tls: 15,
      request: 1,
      firstByte: 36,
      download: 8,
      total: 102
    }
  }
}

**Comment by c0lumb0** [comment]
> Hello
> 
> I tried to login this morning, without success :
> 
> Something went wrong: HTTPError: Response code 403 (Forbidden) at Request. (/usr/local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:117:42) at processTicksAndRejections (internal/process/task_queues.js:97:5) { code: 'ERR_NON_2XX_3XX_RESPONSE', timings: { start: 1647845229734, socket: 1647845229737, lookup: 1647845229763, connect: 1647845229776, secureConnect: 1647845229791, upload: 1647845229792, response: 1647845229828, end: 1647845229836, error: undefined, abort: undefined, phases: { wait: 3, dns: 26, tcp: 13, tls: 15, request: 1, firstByte: 36, download: 8, total: 102 } } }
> 
> I deleted the session info, same result

Did you also do the changes for api.js mentioned here
https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/148#issuecomment-1073048888
?

**Comment by marklagendijk** [comment]
No need to do manual changes / npm installs. The latest version [has the cookieJar applied](https://github.com/marklagendijk/node-toogoodtogo-watcher/commit/50e72668c938a4d013d131f46a2514b88799ab4b).

**Comment by gielk** [comment]
I'm having the same problem. Updated to the latest version but still no success.

Completely removed and reinstalled the package but no success.

```
root@raspberrypi:/home/pi# toogoodtogo-watcher login
Something went wrong: HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/usr/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1647869529616,
    socket: 1647869529627,
    lookup: 1647869529638,
    connect: 1647869529658,
    secureConnect: 1647869529695,
    upload: 1647869529696,
    response: 1647869529734,
    end: 1647869529780,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 11,
      dns: 11,
      tcp: 20,
      tls: 37,
      request: 1,
      firstByte: 38,
      download: 46,
      total: 164
    }
  }
}
```

**Comment by jfadeuilhe** [comment]
I feel less alone :)

**Comment by rubencougil** [comment]
same here

**Comment by EsEnZeT** [comment]
Looks like they might be banning IP's. Try to login also manually from your phone from same IP, I got captcha.

**Comment by jfadeuilhe** [comment]
I disconnected then reconnected on my phone in wifi, with the same IP therefore.

toogoodtogo-watcher login worked "You are now successfully logged in!"

toogoodtogo-watcher watch still makes error

Error during request:
POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
{
    "refresh_token": "e30.e../..aMZg"
}

HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/usr/local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Help !

**Comment by gielk** [comment]
> Looks like they might be banning IP's. Try to login also manually from your phone from same IP, I got captcha.

Same I also got a captcha, multiple times, but unfortunately, it is not affecting the bot.

**Comment by Slothoncrack** [comment]
Same problem here. Didn't see any captchas though.
My fridge is looking sad :(

**Comment by marklagendijk** [comment]
My guess is that there is an issue with the login process.
I didn't do a new login after the changes, and it works fine for me. Others reported the same.

**Comment by Slothoncrack** [comment]
The issue arrived for me without having done anything. It was working fine for months and suddenly i would just get 403s. I only attempted to do a new login a few days ago as it was suggested here, but that didn't solve my problem.

**Comment by jfadeuilhe** [comment]
After a break of a few days, I restart the processes and it works!
The problem must have been linked to the banning IP!

**Comment by Slothoncrack** [comment]
Okay so I forced public IP changes by replugging my router (and verifying), and I logged in again several times successfully, with new access and refresh tokens. But no matter what I do, I still always get 403s. (I'm on the newest tgtg-watcher version of course).

Weird!

**Comment by TwixGamer00** [comment]
is it possible that they've changed endpoints?

**Comment by Slothoncrack** [comment]
I've completely factory reset my Termux now and reinstalled everything from scratch. It works now! No idea what went wrong on my previous setup.

**Comment by marklagendijk** [comment]
Closing this because it seems to be a temporary IP ban issue.
