### ISSUE TITLE
index.js:290  throw error; (InvalidConfig)

### ISSUE THREAD

**Issue by ApophysX** [marklagendijk/node-toogoodtogo-watcher#156]
Hello,

I have made a mistake when entering my token, since then I get these messages.

toogoodtogo-watcher config-path
\node-v16.14.2-win-x86\node_modules\toogoodtogo-watcher\node_modules\conf\dist\source\index.js:290
            throw error;
            ^

SyntaxError: Unexpected token : in JSON at position 731
    at JSON.parse (<anonymous>)
    at Conf._deserialize \node-v16.14.2-win-x86\node_modules\?[4mtoogoodtogo-watcher?[24m\node_modules\?[4mconf?[24m\dist\source\index.js:67:43)
    at Conf.get store [as store] \node-v16.14.2-win-x86\node_modules\?[4mtoogoodtogo-watcher?[24m\node_modules\?[4mconf?[24m\dist\source\index.js:278:43)
    at new Conf node-v16.14.2-win-x86\node_modules\?[4mtoogoodtogo-watcher?[24m\node_modules\?[4mconf?[24m\dist\source\index.js:131:32)
    at Object.<anonymous> \node-v16.14.2-win-x86\node_modules\?[4mtoogoodtogo-watcher?[24m\lib\config.js:5:16)
?[90m    at Module._compile (node:internal/modules/cjs/loader:1103:14)?[39m
?[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)?[39m
?[90m    at Module.load (node:internal/modules/cjs/loader:981:32)?[39m
?[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)?[39m
?[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)?[39m

node-v16.14.2-win-x86>

Whether I used Config Reset or Config Command.

How to reset the Config Manuel?

ps. okay i find the config file C:\Users\...\AppData\Roaming\toogoodtogo-watcher-nodejs\Config

**Comment by c0lumb0** [comment]
There are two config files, which need to be changed in this case.
The first one is the one with the standard values and the other one is the one which is cached I guess and should be found in the directory you've mentioned.
