### ISSUE TITLE
Error Reporting on missing write Permission

### ISSUE THREAD

**Issue by jakobwenzel** [marklagendijk/node-toogoodtogo-watcher#16]
First of all, thanks for the great work!

Due to a configuration error, the program initially did not have write permissions to its config directory. In this case the error message is rather unhelpful:
```
Error undefined during undefined undefinedundefined:
undefined
```

**Comment by marklagendijk** [comment]
I think th0e best solution would be to do a check on startup to see if the config file is writable.

**Comment by jakobwenzel** [comment]
That check does not seem to be enough.
conf writes using the write-file-atomic package, which creates a temporary file first and then renames it to the target filename.

**Comment by marklagendijk** [comment]
Right, we could just check by setting the config to it's current value, and throwing a descriptive exception when it fails.

**Comment by marklagendijk** [comment]
I think the exception will be better now, because [the error handling code](https://github.com/marklagendijk/node-toogoodtogo-watcher/blob/19e45264e13f62dd66f07056d1dc97790a4a2836/lib/poller.js#L49) has been improved
