### ISSUE TITLE
Error 404 during POST https://apptoogoodtogo.com/api/item/v3/:

### ISSUE THREAD

**Issue by BlackMatrix85** [marklagendijk/node-toogoodtogo-watcher#17]
Hi and thanks for your work!

I´ve following error:

Login seems to happen, because I got the new device email then this happens continuely

Error 404 during POST https://apptoogoodtogo.com/api/item/v3/:
undefined

Any suggestions? :/

Thanks in advance

**Comment by btchip** [comment]
As a quick random fix, just replacing v3 by v4 in lib/api.js seems to work

**Comment by marklagendijk** [comment]
@BlackMatrix85 thanks for reporting this issue.
@btchip thanks for the fix. I applied it and released a new version.
I'm not using this tool that often anymore, so it is really valuable that these issues and fixes for them are being reported :+1:
