### ISSUE TITLE
Apprise instead of manually adding notification systems

### ISSUE THREAD

**Issue by schklom** [marklagendijk/node-toogoodtogo-watcher#173]
Instead of coding notification systems one by one (Gotify, Telegram, etc), you may want to code a link to [Apprise](https://github.com/caronc/apprise) which is a gateway to most notification systems.

It requires the user to host an Apprise instance, but would also let the user choose any of the ~80 notification systems supported by it.

Not a priority, but it would be a nice feature :)

**Comment by marklagendijk** [comment]
I like this.
The main way of using this application is via Docker already, and this combines nicely.
It will provide great power at a small cost.

I'm not sure if and when I will get to implementing this, but PRs are welcome.
I will close any notification issues / PRs in favor of this.

**Comment by marklagendijk** [comment]
See #215 .
