### ISSUE TITLE
403 on Login 

### ISSUE THREAD

**Issue by olka276** [marklagendijk/node-toogoodtogo-watcher#180]
Hi! I have a problem with logging into watcher. For some reason, sending notifications of new TGTG offers stopped working. So I uninstalled npm package with watcher and deleted config file. Afterwards, I installed it again, but there is a 403 response when I'm trying to log in. I'm attaching my console screenshot. I will be thankful for any solution, you are making a good job and I appreciate it!
![image](https://user-images.githubusercontent.com/34678773/192870508-388fff4c-72e0-4dda-86fa-498118b10128.png)
![image](https://user-images.githubusercontent.com/34678773/192870776-36de0e02-d6ef-42e6-9057-e2b0d7f18063.png)

Also if you want to improve your watcher I have a suggestion. Sometimes watcher stops working with a "Broken pipe" error. Then I had to turn watching on again and it works. Maybe there is a possibility to fix this as well?
Greetings! :)

**Comment by kwinzig** [comment]
I have basically the same issue, when trying to refesh the token a 403 error is returned.
![image](https://user-images.githubusercontent.com/9356474/193086695-33e76349-46d2-49e2-88f9-0ae74a6ccb7d.png)

**Comment by olka276** [comment]
Finally I logged in, but have a same issue as @kwinzig 😭  @marklagendijk waiting for your help! 🙏

**Comment by NickXDD** [comment]
I've got the same problem a while ago, changing my IPv4 address have helped.

**Comment by goncer** [comment]
ouch! same issue here. Perhaps we got IP-blocked in too good to go ?

**Comment by olka276** [comment]
@NickXDD I am not sure what do you mean. Are you talking about using any VPN or something? How can I change IP address? 😊

**Comment by NickXDD** [comment]
@olka276 You can start by restarting your router, sometimes it works. In general it's dependent on what setup you are using. I'm using an oracle virtual machine that runs the watcher, so in my case it was not that easy obviously.

**Comment by olka276** [comment]
Oh I see. I don't use watcher on my PC, I have a virtual machine. I changed IP address but it did not help :(

**Comment by NickXDD** [comment]
There's a link to another repo which adresses this issue: https://github.com/Der-Henning/tgtg/wiki/FAQ#1-i-am-getting-error-403-all-the-time

**Comment by olka276** [comment]
Thank you @goncer  @NickXDD . I tried to use bot locally on ubuntu and it works. Imo it's a banned IP.  My fridge is not crying now ❤️

**Comment by KaKi87** [comment]
Hello,
I'm experiencing the same issue, although the other project mentioned by @NickXDD works fine on the same computer, so it's not IP-related.
Thanks

**Comment by c0lumb0** [comment]
> I have basically the same issue, when trying to refesh the token a 403 error is returned. ![image](https://user-images.githubusercontent.com/9356474/193086695-33e76349-46d2-49e2-88f9-0ae74a6ccb7d.png)

I got the same issue just yesterday. After trying some stuff, it helped for now to delete the current config and re-login via the process described in the documentation. It works fine for now.
