### ISSUE TITLE
chat_id is empty

### ISSUE THREAD

**Issue by Fullmono** [marklagendijk/node-toogoodtogo-watcher#181]
Hello, 

I struggle to config Telegram notification. Here is my config
![image](https://user-images.githubusercontent.com/4299889/193294194-c457950b-c8e0-4d79-8894-458ecf65735a.png)

I keep getting an error "chat_id is empty" when notification should be triggered. Does anyone have the same problem?
(I use the same botToken and chat_id for other services that works well)

I thus use ifttt to transfert notification towards telegram but It's a workaround.

it would be awesome to integrate apprise to be compatible with all kind of notification services
https://github.com/caronc/apprise

**Comment by nmatton** [comment]
chats should be an object with a "id" key
something like that :
```
		"telegram": {
			"enabled": true,
			"botToken": "<your manually entered token>",
			"chats": [
				{
					"id": ********
				}
			]
		},
```
Did you manually entered your id ? Maybe you should free the content of the chats list you have in your file (to have something similar to the default) and run the /start command again..
