### ISSUE TITLE
Won't work anymore 

### ISSUE THREAD

**Issue by kershin** [marklagendijk/node-toogoodtogo-watcher#182]
Hello, it doesn't work anymore since late September.
I've digged in the application calls and found out that too good to go as implemented datadome protection.

**Comment by nmatton** [comment]
It is still working on my side... maybe refresh your IP that may have been banned?

**Comment by krikk** [comment]
just changed ip, does still not work, always getting 
`HTTPError: Response code 403 (Forbidden)`

**Comment by kershin** [comment]
403 means that all requests from this account is blocked by datadome, waiting for the captcha solving. 😑

**Comment by inject3d** [comment]
Does it still work for people? I just ran the docker but i cannot login. How does it work?

Normally I would execute it like this: "docker exec -it toogoodtogo-watcher sh login"

**Comment by c0lumb0** [comment]
Still works on my side, just checked.

**Comment by moritzhckr** [comment]
Mine Just stopped working this morning, after running perfectly yesterday.
So sad this was a super cool and handy thing, I absolutely loved how it just worked! I hope someone finds a workaround for that.
---
Error during request:
POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
->HTTPError: Response code 403 (Forbidden)

**Comment by Valmlbr** [comment]
Mine stopped today... 
Same error : `HTTPError: Response code 403 (Forbidden)`

**Comment by nmatton** [comment]
Seems related to IP filtering on tgtg side.
The same applies for instance running on heroku. Maybe using a proxy could help, but I'm not sure the way to implement that with got...

**Comment by jozefszymala** [comment]
Same here Polnad RIP :(

**Comment by Juanma24-** [comment]
Hello, 

If it helps, I just did **toogoodtogo-watcher login** (after correctly setting the config file), follwed the instructions, and it worked again when I tried **toogoodtogo-watcher watch**

**Comment by jozefszymala** [comment]
> Hello,
> 
> If it helps, I just did **toogoodtogo-watcher login** (after correctly setting the config file), follwed the instructions, and it worked again when I tried **toogoodtogo-watcher watch**

Hell yeeee it worked, thanks a lot - I tried to login via telegram... forgot to setup from terminal :D

**Comment by fxhuhn** [comment]
@Juanma24-  thanks for remind us to use the login :-)
I guess we need this helpful hint in our REAMDE.ME

**Comment by inject3d** [comment]
Would you have an idea why it's not working?

I enter /login in the bot, open the url from the mail on my computer and press afterwards /login_continue and receive with the accounts details the following:

```
(node:6) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/home/node/.config/toogoodtogo-watcher-nodejs/config.json.tmp-1717962669ee8bdf'
    at openSync (fs.js:497:3)
    at attempt (/home/node/app/node_modules/atomically/dist/utils/retryify.js:33:27)
    at Object.writeFileSync (/home/node/app/node_modules/atomically/dist/index.js:136:49)
    at Conf._write (/home/node/app/node_modules/conf/dist/source/index.js:374:28)
    at Conf.set store [as store] (/home/node/app/node_modules/conf/dist/source/index.js:295:14)
    at Conf.set (/home/node/app/node_modules/conf/dist/source/index.js:188:20)
    at createSession (/home/node/app/lib/api.js:98:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async loginContinueCommand (/home/node/app/lib/telegram-bot.js:168:31)
    at async execute (/home/node/app/node_modules/telegraf/lib/composer.js:458:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
You are not logged in. Login via the command `toogoodtogo-watcher login` or `/login` with the Telegram Bot
```

I don't see any 403 or something similar, therefore I have no ideas.

**Comment by c0lumb0** [comment]
I got this error (more or less) some days ago:

Error during request:
POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
{
"refresh_token": "e30.e../..kLuZT"
}

HTTPError: Response code 403 (Forbidden)
at Request. (local/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:117:42)
at processTicksAndRejections (internal/process/task_queues.js:97:5)

Also deleting the config file, logging in from scratch and working through the process worked as it seems just fine now again. I don't now if this is the final fix ;) Is this really an IP related issue? Since between trying and getting the error and fixing the issue were just some minutes and the IP was or is still the same at least on my side.

**Comment by dennisvanderpool** [comment]
> Would you have an idea why it's not working?
> 
> I enter /login in the bot, open the url from the mail on my computer and press afterwards /login_continue and receive with the accounts details the following:
> 
> ```
> (node:6) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/home/node/.config/toogoodtogo-watcher-nodejs/config.json.tmp-1717962669ee8bdf'
>     at openSync (fs.js:497:3)
>     at attempt (/home/node/app/node_modules/atomically/dist/utils/retryify.js:33:27)
>     at Object.writeFileSync (/home/node/app/node_modules/atomically/dist/index.js:136:49)
>     at Conf._write (/home/node/app/node_modules/conf/dist/source/index.js:374:28)
>     at Conf.set store [as store] (/home/node/app/node_modules/conf/dist/source/index.js:295:14)
>     at Conf.set (/home/node/app/node_modules/conf/dist/source/index.js:188:20)
>     at createSession (/home/node/app/lib/api.js:98:12)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at async loginContinueCommand (/home/node/app/lib/telegram-bot.js:168:31)
>     at async execute (/home/node/app/node_modules/telegraf/lib/composer.js:458:17)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:6) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:6) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> You are not logged in. Login via the command `toogoodtogo-watcher login` or `/login` with the Telegram Bot
> ```
> 
> I don't see any 403 or something similar, therefore I have no ideas.

Permission issue in the config file. The watcher needs to write to the config file as well. See section in README.
