### ISSUE TITLE
no email

### ISSUE THREAD

**Issue by ayarnaud** [marklagendijk/node-toogoodtogo-watcher#183]
Hi,

I try to run this app with node v16.13.1, but I block when I launch  `toogoodtogo-watcher login`
Before, I have edited the `config.json`, especialy this line:   `email":"XXX.YYY@gmail.com`, but I don't receive email.

May I have to configure something else before ?

Sorry if my question is silly :)

Thank you

**Comment by nmatton** [comment]
did you update your email using `toogoodtogo-watcher config ` ?  updating the value of config.default.json won't work (if I'm right^^)
