### ISSUE TITLE
'ERR_NON_2XX_3XX_RESPONSE'

### ISSUE THREAD

**Issue by jbdaskie** [marklagendijk/node-toogoodtogo-watcher#192]
Hello,

I've tried to config this nice code. I've put my email adresse in the config file (nothing more) as it is describe in the readme. But when I try to run : "toogoodtogo-watcher login", there is alway the same issue : "Something went wrong: HTTPError: Response code 403 (Forbidden)"
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: xxx,
    socket: xxx,
    lookup: xxx,
    connect: xxx,
    secureConnect: xxx,
    upload: xxxx,
    response: xxx,
    end: xxx,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 3,
      dns: 10,
      tcp: 14,
      tls: 20,
      request: 1,
      firstByte: 43,
      download: 25,
      total: 116
    }

Have you any advices to fix it ? Thanks for your help and your work.

**Comment by Samor96** [comment]
Same issue here.

**Comment by rrakso** [comment]
Me too :(

**Comment by rrakso** [comment]
Oh @jbdaskie @Samor96 look [here](https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/150#issuecomment-1086616258) 😅

**Comment by marklagendijk** [comment]
Closing as duplicate.
