### ISSUE TITLE
How to start config file

### ISSUE THREAD

**Issue by Pabl0Parra** [marklagendijk/node-toogoodtogo-watcher#194]
After doing  

`1. Install Node.js 14.x or higher 
npm install -g toogoodtogo-watcher`

When I run 
`toogoodtogo-watcher config`

 I received the error that it doesn´t exist, what am I missing?

**Comment by c0lumb0** [comment]
Did you check if the file is really in the correct folder?
If yes, you can change the account details also directly in the config file...I did that in the past when a password was still needed.

**Comment by Pabl0Parra** [comment]
Yes, it's in the right path, so how do u run it once I configure it?

**Comment by Pabl0Parra** [comment]
i was able to run it with "node index config" but now it won´t connect...got a 404 error
