### ISSUE TITLE
Only the first 20 businesses are shown when listFavoriteBusinesses

### ISSUE THREAD

**Issue by yldun** [marklagendijk/node-toogoodtogo-watcher#2]
The response in JSON file shows page_no: 2, limit: 20 outside info.
I don't know how to see others pages.

**Comment by marklagendijk** [comment]
The results are indeed paged.
In general there are two ways to deal with this:
1. Adjust the page size to a bigger size, so you still only have one page (not always supported).
2. Do multiple requests until you get all pages.

If you (or someone else) figures out how the paging works for the TooGoodToGo API, I would be willing to add support for it.

However, I think this application won't work well if you have so many favorites. The amount of SPAM would be too big.
For now I would advise to only add those businesses as favorite which you want to watch. You could even create a separate TooGoodToGo account for that.

**Comment by maxux** [comment]
You can adjust page and page_size (not tested how long it can be) in the item list request:
https://github.com/maxux/toogoodtogo-watcher/blob/master/toogoodtogo.py#L136-L149

**Comment by marklagendijk** [comment]
Since the results are now usually filtered, it should be really rare for this to be a problem.
