### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by earthly-alien** [marklagendijk/node-toogoodtogo-watcher#202]
I'm trying to run the app on docker on my unRAID server, but I can't get it to work.

If I install it through docker compose and then start the container, the logs say ```You are not logged in. Login via the command `toogoodtogo-watcher login` or `/login` with the Telegram Bot```. However, when I attempt to do it with `docker exec -it <container_name> toogoodtogo-watcher login`, I get an error message `Error response from daemon: Container <id> is restarting, wait until the container is running`.

I'm not sure what I'm doing wrong.

**Comment by dennisvanderpool** [comment]
It supplied a second option, did you try that one as well?
_"or `/login` with the Telegram Bot"_

**Comment by dennisvanderpool** [comment]
I could login via the Telegram method. Still I don't get any updates on my favorites though.

**Comment by earthly-alien** [comment]
The thing is, I can't execute any command within the container, because the container itself is in a boot-loop, as per the error.

**Comment by dennisvanderpool** [comment]
Could be permission issue? I need to read the config file, maybe temporary give it more rights on the config file/dir.

**Comment by dennisvanderpool** [comment]
When I disable the Telegram plugin, I'm also in a boot loop, bot seems to work and with Telegram I can start/stop notifications, change what I want to receive notifications about, but I don't receive any notifications.

So, now for debugging purposes I've disabled the Telegram notification and just use console, I'm now also in the same boot loop. To be continued... 😊

**Comment by earthly-alien** [comment]
Enabling Telegram bot stopped the looping, but I believe the fault is entirely my own for the app not working, and it's got to do with Node.js. I tested it on my Linux desktop and it works fine (minus the fact that I get Error 403). I will close this issue for the time being.
