### ISSUE TITLE
Does it still work? I don't get any notifications

### ISSUE THREAD

**Issue by dennisvanderpool** [marklagendijk/node-toogoodtogo-watcher#203]
I seem to have setup everything correctly, but I don't get any notifications.
I've used it numerous times in the past and worked fine.
Telegram bot is connected and I can modify the subscriptions and it will modify the config.json file fine.
I've also set everything to true in the message filter and enabled both Telegram and console.

Does it still work for somebody? If it is I know it must be something on my end, but I've now tried it for hours and can't find an easy way to debug it.

**Comment by c0lumb0** [comment]
Do you get any error messages?

**Comment by dennisvanderpool** [comment]
No, that's the problem, I don't get any error messages. I looks like it doesn't see my favorite stores or something like it as no error are coming. Would be nice to have some debugging commands in the bot/command line for troubleshooting.

**Comment by c0lumb0** [comment]
> No, that's the problem, I don't get any error messages. I looks like it doesn't see my favorite stores or something like it as no error are coming. Would be nice to have some debugging commands in the bot/command line for troubleshooting.
> 
> I still plan to debug it by tcpdump and decrypt the https traffic, but a simpler solution for debugging would be nice 😁

Ah, ok.
I had this behavior once, when I reinstalled the application from scratch and forgot to start the application with /start in the telegram bot so that notifications are triggered. Maybe on your side, its the same or similar?

**Comment by dennisvanderpool** [comment]
Nope, sorry, did recreate it from scratch multiple times, that isn't the issue 😊

**Comment by marklagendijk** [comment]
See solution in #201.
