### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by maxijilka** [marklagendijk/node-toogoodtogo-watcher#204]
Hello,

first of all thanks for this great tool, however I receive this error. Any way to fix this?
![dfredef](https://user-images.githubusercontent.com/69720665/214138489-9511a43a-b562-4b4d-8824-8e524d413593.PNG)

**Comment by c0lumb0** [comment]
> Hello,
> 
> first of all thanks for this great tool, however I receive this error. Any way to fix this? ![dfredef](https://user-images.githubusercontent.com/69720665/214138489-9511a43a-b562-4b4d-8824-8e524d413593.PNG)

A first solution to this issue is described in
https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/201

**Comment by marklagendijk** [comment]
Closing as duplicate.
