### ISSUE TITLE
Feature : multi-users

### ISSUE THREAD

**Issue by koff75** [marklagendijk/node-toogoodtogo-watcher#21]
Hi ! 
I appreciate your work 👍 

Would love to implement multi-users on one Telegram bot.
I tried to observe the changes when addChat() is called, then subscribe to pollBusinesses() for a specific user id.
Same for removeChat(), I would unsubscribe the pollBusinesses() for a specific user id.

Do you have any idea to manage the subscriptions easily ?

Thanks =)

**Comment by marklagendijk** [comment]
I assume that by multiple users, you mean multiple TGTG users? Because you can already use the Telegram bot with multiple Telegram users.

I wouldn't add support for multiple TGTG users. I would instead advise to run a Docker container with its own Telegram bot per TGTG user.

**Comment by ssergiio** [comment]
Hi!

It is possible to run multiple instances of the cli tool on the same server?

**Comment by koff75** [comment]
For sure, you just have to have multiple directories. Then just execute: `pm2 start index.js`
If you want to manage your 'pms', change the name in each dir', eg: "index_1.js".

**Comment by marklagendijk** [comment]
Multi user won't be supported. It adds quite some complexity and you can already solve it by running the app multiple times.
