### ISSUE TITLE
messageFilter not working

### ISSUE THREAD

**Issue by fxhuhn** [marklagendijk/node-toogoodtogo-watcher#217]
Does anyone have the same problem that the filters no longer work in version 4.0?
For each change, I get sent all observations, including those with quantity 0.

So far the filters have always worked, so I don't think there is any error in the configuration.

`

    "messageFilter": {

		"showUnchanged": false,
		"showDecrease": true,
		"showDecreaseToZero": false,
		"showIncrease": true,
		"showIncreaseFromZero": true
	}
`

**Comment by marklagendijk** [comment]
This was indeed a bug that was introduced in version 4.
Fixed now and released as `4.0.2`.
