### ISSUE TITLE
Auth version from v3->v4

### ISSUE THREAD

**Issue by c0lumb0** [marklagendijk/node-toogoodtogo-watcher#252]
Since the application stopped working yesterday all of a sudden, I checked the TGTG applications here in Github and found this here:

https://github.com/Der-Henning/tgtg/pull/553/commits/9af648a0cecd74df88ef9a50502159db13b1d451

and applied this also to this application, which made it working again when the 3 endpoints in the API are changed from v3 to v4.

**Comment by sebastianklein96** [comment]
Nice catch! Did you have to reauth?

**Comment by TP8609** [comment]
I did not had to reaut changed it in this file:
lib/toogoodtogo-api.js 

Just find all the v3 and change it to v4.

and start watcher again all good !

**Comment by marklagendijk** [comment]
Fixed in `4.0.5`.
