### ISSUE TITLE
Feature request: automatically purchasing

### ISSUE THREAD

**Issue by martinbaste** [marklagendijk/node-toogoodtogo-watcher#29]
Hi,

Some stores last seconds available. I don't know the details of how implementing purchasing within the bot would be. Does anyone have any pointers? I could look into it but not sure where to start.

**Comment by TanguyOrtegat** [comment]
In the script here is an example already how to add in basket, but now is how to implemente payments... 
https://github.com/maxux/toogoodtogo-watcher/blob/master/toogoodtogo.py#L218

**Comment by marklagendijk** [comment]
For me automatic purchasing is one step too far.
