### ISSUE TITLE
Manage toogoodtogo errors

### ISSUE THREAD

**Issue by Fullmono** [marklagendijk/node-toogoodtogo-watcher#3]
Hello, 

Toogoodtogo is down this morning. It could be great to manage these errors instead of stopping the service.

`'<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor="white">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n'`

(or getting a notification in case of errors)

**Comment by marklagendijk** [comment]
This should now be fixed in the latest version (1.2.1).
