### ISSUE TITLE
400 - Bad Request: message text is empty

### ISSUE THREAD

**Issue by kakauko66** [marklagendijk/node-toogoodtogo-watcher#30]
Hi, this is my first time trying to run script like this. Im getting the message below in console and I don't know what to do about it :)

C:\Windows\system32>toogoodtogo-watcher watch
Added chat Maciej undefined (1262809328)
400 - Bad Request: message text is empty

**Comment by andreaseide80** [comment]
Please check your config.
You need to enable at least one of the filters in the config.

**Comment by kakauko66** [comment]
Telegram was already enabled

**Comment by andreaseide80** [comment]
Check this part :  
"messageFilter": {
    "showUnchanged": false,
    "showDecrease": false,
    "showDecreaseToZero": false,
    "showIncrease": false,
    "showIncreaseFromZero": true
  }

At least one of these need to be true. 
You might still get one 400 message empty, but it should work if one is true.

**Comment by kakauko66** [comment]
That's also not it ;)
{
	"api": {
		"credentials": {
			"email": "---",
			"password": "---"
		},
		"session": {
			"userId": "22102871",
			"accessToken": "---",
			"refreshToken": "---"
		},
		"headers": {
			"User-Agent": "TooGoodToGo/20.6.1 (813) (iPhone/iPhone 7 (GSM); iOS 13.6; Scale/2.00)"
		},
		"pollingIntervalInMs": 1000,
		"authenticationIntervalInMS": 3000
	},
	"notifications": {
		"console": {
			"enabled": false,
			"clear": true
		},
		"desktop": {
			"enabled": false
		},
		"telegram": {
			"enabled": true,
			"botToken": "---",
			"chats": [
				{
					"id": 1262809328,
					"firstName": "Maciej"
				}
			]
		}
	},
	"messageFilter": {
		"showUnchanged": false,
		"showDecrease": false,
		"showDecreaseToZero": false,
		"showIncrease": false,
		"showIncreaseFromZero": true
	}
}

**Comment by andreaseide80** [comment]
I think it's just a start message.
Could you just try to set showUnchanged to true and test once? Maybe set console to true to see messages in the console as well. 
I also think your interval is too short. Once every second. And authentication every 3 seconds. 
Doing it too often would block your IP on TGTGs servers. 
Maybe set 20000 (20sec) and 120000(120sec)

**Comment by kakauko66** [comment]
Yeah, now it's spamming with 0 packages across places every 20 seconds :). So at least thats good. Probably you're right about timers. Thank you very much <3, I will close this if normal notification will apper, but thats probably going to happen tomorrow due late time.
