### ISSUE TITLE
standard_init_linux.go: 211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by aperezna** [marklagendijk/node-toogoodtogo-watcher#33]
Hello, thank you very much for your work,

I am trying the DOCKER installation of your development. When launching the following instruction:

docker run --name toogoodtogo-watcher -v / home / pi / config marklagendijk / toogoodtogo-watcher

It throws me the following error:

pi @ raspberrypi: ~ $ sudo docker run --name toogoodtogo-watcher -v / home / pi / config marklagendijk / toogoodtogo-watcher
Unable to find image 'marklagendijk / toogoodtogo-watcher: latest' locally
latest: Pulling from marklagendijk / toogoodtogo-watcher
cbdbe7a5bc2a: Pull complete
338e24a1fcf8: Pull complete
68c2b1f63a50: Pull complete
70840f95d8e3: Pull complete
e33910ba3fe4: Pull complete
e39d46dd4076: Pull complete
734716a8bbf9: Pull complete
a35067829acc: Pull complete
663686d91520: Pull complete
Digest: sha256: 789fcf20ba519b9f467a4c43579b42db8fde2d934525311ba91a77f89cece5ef
Status: Downloaded newer image for marklagendijk / toogoodtogo-watcher: latest
standard_init_linux.go: 211: exec user process caused "exec format error"

I don't understand the reason for the error, can you help me?

Greetings and thanks,
Alex

**Comment by pbakun** [comment]
You can build an image yourself using Dockerfile provided in repo. I recommend filling your config in config.defaults.json.
Later if you want to edit anything you can explore container files with:
`docker exec -it <container_name> /bin/sh`

**Comment by marklagendijk** [comment]
I added instructions to the README: https://github.com/marklagendijk/node-toogoodtogo-watcher#docker-compose-on-raspberry-pi
