### ISSUE TITLE
Self signed certificate error with "watch" command

### ISSUE THREAD

**Issue by NessunoIM** [marklagendijk/node-toogoodtogo-watcher#35]
After installation if I run "toogotogo-watcher config" I can set properly my credentials, but after I run "toogotogo-watcher watch" I see this error: RequestError: self signed certificate in certificate chain.

I tried "npm set strict-ssl false" without success.

**Comment by marklagendijk** [comment]
Could be that your version of node is outdated. Try updating.
Better yet, run it via Docker instead, so it just works :).
