### ISSUE TITLE
CLI in docker container

### ISSUE THREAD

**Issue by schklom** [marklagendijk/node-toogoodtogo-watcher#38]
Hi, I love your app :)

I am using it from your website for now, and am trying to switch to the Docker image to lift the 5 shops restriction, but I'm getting stuck.

How do I do any `toogoodtogo-watcher` commands in a docker container ?

I don't know if it's running properly because the logs are empty.

Example of what I tried
```
$ docker exec toogoodtogo-watcher sh -c 'toogoodtogo-watcher --help'
sh: toogoodtogo-watcher: not found
```

**Comment by bokkoman** [comment]
I'm also not very experienced with docker. But i believe you have to use bash to use commands within a container.
Or use something like Portainer maybe?

**Comment by schklom** [comment]
$ docker exec -it toogoodtogo-watcher bash
    OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "bash": executable file not found in $PATH: unknown

`bash` doesn't seem to work for the container, only `sh`.
`sh -c 'toogoodtogo-watcher --help'` is a way to pass more than 1 argument to `docker exec` without having to open a terminal into the container with `docker exec -it toogoodtogo-watcher sh` and then type `toogoodtogo-watcher --help`

**Comment by bokkoman** [comment]
Why do you need to do commands in the container exactly? There is no need for it. You only have to edit the config and put it somewhere and link to it when you start. There is not much editing.

**Comment by schklom** [comment]
I didn't have any console output despite turning it on, so I wanted to see what was going on with `config` and `watch`.
It turns out I had forgotten to write `true` in the console notifications part of the `config.json`, I'm an idiot x)

However, it would still be interesting to know how to run the `toogoodtogo-watcher ...` commands in the container.

**Comment by schklom** [comment]
I found out ! The key was in the Dockerfile's last line which shows how to run a command.
In case anyone is interested, I'll post the solution here and close this issue :)

`toogoodtogo-watcher command` is equivalent inside the Docker container to `node /home/node/app/index.js command`
or from the host directly: `docker exec toogoodtogo-watcher sh -c 'node /home/node/app/index.js command'`
