### ISSUE TITLE
Launch failed Error: 401: Unauthorized

### ISSUE THREAD

**Issue by c0lumb0** [marklagendijk/node-toogoodtogo-watcher#40]
Hi,

this is an awesome app especially with the telegram messages!! 👍 
Unfortunately with NodeJS I get the response

Launch failed
Error: 401: Unauthorized
    at C:\Users\erich\node_modules\telegraf\core\network\client.js:281:17
    at processTicksAndRejections (node:internal/process/task_queues:93:5)

Anyone seen this before?

Credentials are fine, since I get the new log in mail by TGTG.
User agent is correct as well as the API v5 for listFavoriteBusinesses()

Any ideas?

Thx in advance

**Comment by bokkoman** [comment]
It says unauthorized, maybe a permission is set wrong?

**Comment by c0lumb0** [comment]
Hm...since I didn't change any settings execpt for the credentials and the telegram bot token, there're all set to defaut values. Or which other permissions could this be? OS permissions?

**Comment by bokkoman** [comment]
>  OS permissions?

Yes, that is what I meant. These files need to be accessible by the node user of this watcher. I had a similar problem. It helped to chmod the files to 2755.

**Comment by c0lumb0** [comment]
I tried to run cmd.exe / nodejs command prompt as administrator but the result is still the same.
Is

_C:\Users\erich\node_modules\telegraf\core\network\client.js:281:17_
_at processTicksAndRejections (node:internal/process/task_queues:93:5)_

giving any hints on the cause of the issue?

**Comment by bokkoman** [comment]
I don't know. Maybe use it in a docker? For me that works.

**Comment by c0lumb0** [comment]
Ok, I could do that...since I didn't use Docker before, I wanted to stick with NodeJS.

If anyone encounters the same issue and has an idea for a solution, pls tell me. Thx.
