### ISSUE TITLE
API v5 --> v6

### ISSUE THREAD

**Issue by c0lumb0** [marklagendijk/node-toogoodtogo-watcher#42]
Hi,

just noticed that they have updated the API once more so that just like here

https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/22#issuecomment-686280012

you need to update the the value from v5 to v6.
Just did that and it worked again. Just in case you're getting the 404 error.

**Comment by PtiBen69** [comment]
Could you create a pullrequest ?

**Comment by andreaseide80** [comment]
Pr approved

**Comment by marklagendijk** [comment]
Done
