### ISSUE TITLE
Error with config command on RPi + setup for pm2?

### ISSUE THREAD

**Issue by ffd8** [marklagendijk/node-toogoodtogo-watcher#54]
Tried to get running on an RPi and get the following error when using the `config` command:
```
Saved config at:  /home/pi/.config/toogoodtogo-watcher-nodejs/config.json
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn vim ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Any idea what the problem might be? 
I did have to install using `sudo` with npm, as there was an error without.

Nevertheless, could set the config file manually with `nano` on that path and seems to work.. got the telegram bot setup etc...

Lastly, any advice/experience on setting this up with [pm2](https://pm2.keymetrics.io/)? Tried to add the 'watch' command to the start but seemed to fail...

**Comment by marklagendijk** [comment]
No idea. Apparently the editor (vim) exited with an error code.
I would advice using Docker Compose instead of pm2.

pm2 can also work. You just need to consider which user it will run as, because that determines where it looks for the config file.

**Comment by ffd8** [comment]
Ugggh, figured out the pm2 issue.. it has built in `--watch` and to add arguements to a script, there's a few ways – one of which is to add `--` then your args.. turns out it needed to have a space:
`pm2 start index.js --name tgtg -- watch`

All good now and running smoothly in background.

The docker instructions could benefit from a few tips for the uninitiated (noobs).
Wasn't clear which (if any) lines need to be customized to get it running.
Guessing this one, but that `:` throws me off:
`-v /full/path/to/config:/home/node/.config/toogoodtogo-watcher-nodejs \
 marklagendijk/toogoodtogo-watcher` 
(is that [last line](https://github.com/marklagendijk/node-toogoodtogo-watcher/blame/master/README.md#L79) with an extra *\`* intentional? typo from markdown or part of `docker run` syntax?)

**Comment by marklagendijk** [comment]
@ffd8 I made the README a bit more n00b-proof ;)
