### ISSUE TITLE
Unable to get Telegram working

### ISSUE THREAD

**Issue by CorentinDy** [marklagendijk/node-toogoodtogo-watcher#57]
Hi,
I've just set up toogoodtogo-watcher
The notifications in the console are working great but when I try to set up Telegram notification, nothing happen.

I'm used to Telegram bot with token creation but this time nothing, no error messages in toogoodtogo, no nothing.

Did I missed something ?

```
{
  "api": {
  "credentials": {
	  "email": "******************",
	  "password": "******************"
  },
  "session": {
	  "userId": "940629",
	  "accessToken": "********************************",
	  "refreshToken": "*******************************"
  },
  "headers": {
	  "User-Agent": "TooGoodToGo/20.6.1 (813) (iPhone/iPhone 7 (GSM); iOS 13.6; Scale/2.00)"
  },
  "pollingIntervalInMs": 30000,
  "authenticationIntervalInMS": 3600000
  },
  "notifications": {
  "console": {
	  "enabled": false,
	  "clear": true
  },
  "desktop": {
	  "enabled": false
  },
  "telegram": {
	  "enabled": true,
	  "botToken": "********************************",
	  "chats": []
  },
  "ifttt": {
	  "enabled": false,
	  "webhookKey": "see README",
	  "webhookEvents": [
		  "see README"
	  ]
  }
  },
  "messageFilter": {
  "showUnchanged": false,
  "showDecrease": false,
  "showDecreaseToZero": false,
  "showIncrease": true,
  "showIncreaseFromZero": true
}
}
```

Is there something related to the `chats` array in Telegram ?

**Comment by BourgeoisBenjamin** [comment]
Do you see your chat ID in the `chats` array after sending /start to your Telegram bot ?

**Comment by CorentinDy** [comment]
Nope

**Comment by BourgeoisBenjamin** [comment]
I think the bot does not detect you. Try to add debug in the startCommand (https://github.com/marklagendijk/node-toogoodtogo-watcher/blob/4b6ee45d3f55a1056b29c90175b27c1add23876c/lib/telegram-bot.js#L97) function for exemple to see if the bot received "/start" message you sent

**Comment by CorentinDy** [comment]
I've just use another bot token and now it's working perfectly.. so it's not related to your project !

Sorry for this issue and thank you for the work you have done
