### ISSUE TITLE
How to get Docker running?

### ISSUE THREAD

**Issue by Frankdoc** [marklagendijk/node-toogoodtogo-watcher#61]
I'm having issues getting this to run on a docker container on my Synology NAS.

Anyone who can help me out getting this to work?

**Comment by bokkoman** [comment]
Maybe you can explain what you are having trouble with?

**Comment by fxhuhn** [comment]
Hi @Frankdoc ,

please check the following settings:
- Rights for ini file
![docher_rights](https://user-images.githubusercontent.com/49436733/109495379-7c583680-7a8f-11eb-87ba-58115c56a2b1.PNG)
- Path settings
![docker_path](https://user-images.githubusercontent.com/49436733/109495381-7cf0cd00-7a8f-11eb-9215-6669216d4d94.PNG)

**Comment by Frankdoc** [comment]
> Hi @Frankdoc ,
> 
> please check the following settings:
> 
> * Rights for ini file
>   ![docher_rights](https://user-images.githubusercontent.com/49436733/109495379-7c583680-7a8f-11eb-87ba-58115c56a2b1.PNG)
> * Path settings
>   ![docker_path](https://user-images.githubusercontent.com/49436733/109495381-7cf0cd00-7a8f-11eb-9215-6669216d4d94.PNG)

Hi,

I have tried your settings but it does not seem to work. This is what I see in the log:
![log](https://user-images.githubusercontent.com/4076185/111375996-34e0c580-869f-11eb-9321-cb030fb100d0.jpg)

**Comment by bokkoman** [comment]
@Frankdoc 
Can you post your settings of docker?

**Comment by Frankdoc** [comment]
> @Frankdoc
> Can you post your settings of docker?
> 
> Did you create a folder in one of your shares for the config.json?
> 
> Do you know how to SSH into your system?

Hi,
I used the 'docker' folder that was created when I installed docker package.
In that docker folder I created a folder 'toogoodtogo' when the config.json resides.
Below some screenshots of the container.
Concerning SSH: I can use the 'terminal' window 
![Screenshot_4](https://user-images.githubusercontent.com/4076185/111489882-d832e880-873a-11eb-8e47-c7621a903506.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/4076185/111489886-d8cb7f00-873a-11eb-9e7b-396b7cb2ed7a.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/4076185/111489887-d8cb7f00-873a-11eb-940b-dd1be21f68ff.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/4076185/111489888-d8cb7f00-873a-11eb-9856-7ea5aaa70fde.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/4076185/111489890-d9641580-873a-11eb-8c5f-0c8b9a5c292b.jpg)

**Comment by bokkoman** [comment]
@Frankdoc 
Settings look good.
Did you put the config.json file permission to everyone? Maybe put the folder to everyone as well.
If that doesn't work, you might have to use putty to chmod the folder/file. 
Because it looks like a permission error.

**Comment by Frankdoc** [comment]
@bokkoman solved it by changing the permissions on the folder as well! The time in Telegram is off by 1 hour though, will check if my NAS uses the correct time, but its not really an issue. Thx for your help!

**Comment by bokkoman** [comment]
@Frankdoc 
Maybe there is a setting in the settings file to adjust the time? Or a variable in the docker to set the time zone, some containers need that. You have to ask @marklagendijk if this is possible.

**Comment by marklagendijk** [comment]
You can set the timezone by setting the `TZ` environment variable. See [README](https://github.com/marklagendijk/node-toogoodtogo-watcher#docker-compose).

**Comment by bokkoman** [comment]
@Frankdoc there is your answer 😄 
Thanks @marklagendijk.
I think this issue can be closed. Have fun with your watcher!

**Comment by Frankdoc** [comment]
@bokkoman @marklagendijk  sorry to reopen this, but do you know how I can access (and change) that run command? Now I just 'started' the container and it went automatically.
What's the standard timezone, because on my main PC I did not have to change this ( I'm in Europe/Amsterdam) timezone.

**Comment by bokkoman** [comment]
@Frankdoc 
You don't have to run a command.
You go to the container settings, go to tab Environment. Click the big plus (+) and there you put this:
TZ (left entry) = Europe/Amsterdam (right entry).
