### ISSUE TITLE
HTTPError: Response code 401 

### ISSUE THREAD

**Issue by fxhuhn** [marklagendijk/node-toogoodtogo-watcher#62]
Hi there,
i got the following error:
```
HTTPError: Response code 401 (Unauthorized)
    at onResponse (/home/node/app/node_modules/got/dist/source/as-promise/index.js:142:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Error during request:
POST https://apptoogoodtogo.com/api/item/v7/

```
A refresh of the session does not helped, the error is still there. 
Any ideas how to fix it?

**Comment by c0lumb0** [comment]
Did you change anything regarding the version of the api? I didn't see a v7 before, I think.
Once in a while they update their apis, so that this has to be done also in the config e.g. here
https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/42

**Comment by fxhuhn** [comment]
I'm running the docker version without any customizing on my Synology from https://registry.hub.docker.com/r/marklagendijk/toogoodtogo-watcher/

Now it gets a bit mysterious ;-)

**Comment by Frankdoc** [comment]
I have the same error in my logs. Also a 'failed to fetch update to telegram api'

**Comment by JTson8** [comment]
I am also having the same error after trying to run in docker. Any fix found yet?

**Comment by marklagendijk** [comment]
Is this still an issue? If so, can someone try [this change](https://github.com/marklagendijk/node-toogoodtogo-watcher/pull/66/files) and see if that fixes it?

**Comment by JTson8** [comment]
Yep that fixed it for me.
I did however have to also remove all previous session data from the config.

**Comment by MarioVilas** [comment]
Hi. I tried the change as suggested by @marklagendijk but it did not work for me, I'm still getting a 403 error during login.

**Comment by marklagendijk** [comment]
If you install the latest version it should work.
