### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by cizio** [marklagendijk/node-toogoodtogo-watcher#64]
Hi,
i got the following error:
`EACCES: permission denied, open '/home/node/.config/toogoodtogo-watcher-nodejs/config.json.tmp-5366961130cd3aab'`
This error occurred as soon as the container was started.
Whether the volue is a docker volume or a directory
Thanks

**Comment by Frankdoc** [comment]
Got the same issue ( see my other issue)

**Comment by luisluet** [comment]
I'm having exactly the the same issue

**Comment by bokkoman** [comment]
Read solved issues. You are going to bed to change permissions to your folder & file where the config is stored.

**Comment by dennisvanderpool** [comment]
I was also plagued by the issue. Found out the issue and created a PR for it. #77 
I think if that PR is merged the issue will be resolved as well.

**Comment by marklagendijk** [comment]
The PR is merged. Please try the latest version.
