### ISSUE TITLE
Running from heroku gives an diffrent time zone?

### ISSUE THREAD

**Issue by rayhvh** [marklagendijk/node-toogoodtogo-watcher#69]
Im running on an us server. the time seems to be off by 2 hours earlier when ran from heroku then local. ive changed the coordinates in the api.js to rotterdam without luck.

**Comment by marklagendijk** [comment]
You need to specify the timezone in the `TZ` environment variable. See [README](https://github.com/marklagendijk/node-toogoodtogo-watcher#docker)
