### ISSUE TITLE
feature: slack notification

### ISSUE THREAD

**Issue by tomsquest** [marklagendijk/node-toogoodtogo-watcher#7]
Hi,

Nice work !

I do not use Telegram and would like to run this selfhosted (without a terminal) and I am on Slack for work all day. Do you think adding a slack notification would be possible ?

Thanks a lot,
Tom

**Comment by marklagendijk** [comment]
Thanks!
I don't use Slack. I'm not sure how hard it would be. I would accept a pull request on this, but probably won't implement it myself.

**Comment by tomsquest** [comment]
I am sorry for creating this issue, and wanted to apologize. I do know that maintaining software, like this one, is done on your private time. This was just an idea I had, like "oh, that would be cool if..." and I created this issue without thinking about it and mainly about the time it will take to do it, document it and maintain it.
I will close it until I make a PR or do some other stuff.

**Comment by marklagendijk** [comment]
Don't be sorry. Suggestions should be welcome on any open source project.
It might have been that your suggestion would also be useful to me, or that I would like to implement it anyway, or that someone would.

**Comment by Waterstraal** [comment]
I added support for IFTTT integration in #10. Currently that PR doesn't yet support sending values to IFTTT, but that shouldn't be too hard to add. Then you could use IFTTT to integrate Slack quite easily. If #10 could be merged, I could take a look 👍

**Comment by marklagendijk** [comment]
IFTT PR is merged, so it should work now.
