### ISSUE TITLE
Error 403 during POST; Failed Login

### ISSUE THREAD

**Issue by freemann** [marklagendijk/node-toogoodtogo-watcher#8]
I getting, "out of nowhere", this error;
Error 403 during POST https://apptoogoodtogo.com/api/auth/v1/loginByEmail:
```
[
    {
        "code": "FAILED_LOGIN"
    }
]
```

Any idea whats happening or how to sove?

This my postman NodeJS Request code;
```
var request = require('request');
var options = {
  'method': 'POST',
  'url': 'https://apptoogoodtogo.com/api/auth/v1/loginByEmail',
  'headers': {
    'User-Agent': 'TGTG/19.12.0 (724) (Android/Unknown; Scale/3.00)',
    'Content-Type': 'application/json',
    'Accept': 'application/json',
    'Accept-Language': 'en-US'
  },
  body: JSON.stringify({"device_type":"UNKNOWN","email":"xxx@xxxx.nl","password":"xxxxx"})

};
request(options, function (error, response) { 
  if (error) throw new Error(error);
  console.log(response.body);
});
```
Above code returns a full response from the API and with the same credentials my docker container fails.

**Comment by freemann** [comment]
Ok, after some debugging its the config.json the script can't read.
Also when it can read config.json, I get all sorts of chown/rename errors.

I have 15+ docker containers running without any problems and don't want to change any stuff on my running environment. Do you have some advice on how to run this container with docker-compose? I think is user/permissions related, but can't get the finger behind it...

Hope you or somebody else can help.

**Comment by marklagendijk** [comment]
What is your docker-compose configuration for this?
See the relevant section of the [README](https://github.com/marklagendijk/node-toogoodtogo-watcher#docker-compose). Be sure to mount the whole folder that config.json is contained in, not just the config.json file.

**Comment by freemann** [comment]
Here the relevant part of my docker-compose;
```
version: '3.6'
services: 
  toogoodtogo-watcher:
    container_name: toogoodtogo-watcher
#    user: "root"
#    environment:
#      - PUID=1000
#      - PGID=1000
    image: marklagendijk/toogoodtogo-watcher
    restart: unless-stopped
    volumes:
      - /opt/docker/config_toogoodtogo:/home/node/.config/toogoodtogo-watcher-nodejs
```

On the host:
```
marco@docker-one:/opt/docker/config_toogoodtogo$ pwd
/opt/docker/config_toogoodtogo
marco@docker-one:/opt/docker/config_toogoodtogo$ ls -all
total 12
drwxr-xr-x+  2 root root 4096 mrt 30 21:08 .
drwxrwxr-x+ 27 root root 4096 mrt 30 20:57 ..
-rwxrwxr--+  1 root root  654 mrt 30 20:24 config.json
marco@docker-one:/opt/docker/config_toogoodtogo$
```

In the container it looks like;
```
~/.config/toogoodtogo-watcher-nodejs $ pwd
/home/node/.config/toogoodtogo-watcher-nodejs
~/.config/toogoodtogo-watcher-nodejs $ ls -all
total 12
drwxr-xr-x    2 root     root          4096 Mar 30 19:08 .
drwxr-sr-x    3 node     node          4096 Jan 18 16:04 ..
-rwxrwxr--    1 root     root           654 Mar 30 18:24 config.json
~/.config/toogoodtogo-watcher-nodejs $
```

The files match on date and size, also the content is the same.
When I run the container from Portainer i get;
```
2020-03-30T18:57:39.871012383Z Error undefined during undefined undefinedundefined:
2020-03-30T18:57:39.871085478Z undefined
2020-03-30T19:04:33.493249142Z Error undefined during POST https://apptoogoodtogo.com/api/auth/v1/loginByEmail:
2020-03-30T19:04:33.493305661Z undefined
2020-03-30T19:06:38.172883415Z Error undefined during undefined undefinedundefined:
2020-03-30T19:06:38.172916368Z undefined
2020-03-30T19:08:39.785840071Z Error undefined during undefined undefinedundefined:
2020-03-30T19:08:39.785885532Z undefined
```

running it in the container also gives the same error;
```
~/app $ pwd
/home/node/app
~/app $ nodejs index.js watch
Error undefined during undefined undefinedundefined:
undefined
~/app $ nodejs index.js config-path
The config is stored at: /home/node/.config/toogoodtogo-watcher-nodejs/config.json
```

On the some moment I restart the container, I receive a mail van TGTG a new device logged in.
I dubble/triple checked the credentials and the are good.
No idea whats happening here, hope you have
