### ISSUE TITLE
Docker - config always overrides by default

### ISSUE THREAD

**Issue by pawelkw** [marklagendijk/node-toogoodtogo-watcher#89]
I've follow the docker-compose instructions and my config file always gets overridden resulting in the following logs:

```
Error during request:,
POST https://apptoogoodtogo.com/api/auth/v1/loginByEmail,
{,
    "device_type": "UNKNOWN",,
    "email": "Email of your TooGoodToGo account.",,
    "password": "Password of your TooGoodToGo account.",
},
,
HTTPError: Response code 403 (Forbidden),
    at onResponse (/home/node/app/node_modules/got/dist/source/as-promise/index.js:142:28),
    at processTicksAndRejections (internal/process/task_queues.js:95:5),
```

**Comment by marklagendijk** [comment]
I think you didn't follow the instructions exactly correct.
1. You need to put the config file with the correct name in a folder.
2. You need to mount that folder into Docker at the correct location

If you do that, it should work.
