### ISSUE TITLE
Feature request: Only update the favorite tgtg businesses if someone is in the telegram bot

### ISSUE THREAD

**Issue by Logimann** [marklagendijk/node-toogoodtogo-watcher#9]
First of all I would like to thank you for the great work! 

I have a pi.hole and I noticed that the script is making a lot of requests to apptoogoodtogo.com. Every 30 seconds, day and night. I am aware that I can change this in the config. I only use the telegram bot integration, is it possible there if I stop the bot with /stop, that it stops sending requests to apptoogoodtogo.com. In the cli I see my instance of the telegram chat. I would like to do this myself but unfortunately I don't understand JavaScript enough.

It would also reduce the load on the server and prevent tgtg from changing the API again. Due to unintended use of the tgtg API.

**Comment by Waterstraal** [comment]
Good idea! But maybe a separate command would be better to stop polling (`/stopPolling`?), so this won't interfere with other notification services such as console or desktop notifications. 

Alternatively, we could add a polling window in the config to limit requests to the toogoodtogo api. E.g. only poll between 5pm and 6pm.

**Comment by Waterstraal** [comment]
I see that pause and speedup has already been implemented in [toogoodtogo-watcher](https://github.com/maxux/toogoodtogo-watcher): https://github.com/maxux/toogoodtogo-watcher/blob/master/config.sample.py

**Comment by fabgui** [comment]
@Logimann , you could simply schedule the script through cron; eg, add the line below in cron to run the TGTG watcher everyday at 15:30 for 90 minutes:
30 15 * * * /usr/bin/timeout 90m /usr/bin/toogoodtogo-watcher watch

You can also check my slight addition to pause the bot notifications until the next day: send /stop to stop receiving notifications or send /pause to stop just for the day.
https://github.com/marklagendijk/node-toogoodtogo-watcher/pull/12

**Comment by fabgui** [comment]
@Logimann , I added the function to stop the polling when Telegrma is enabled but noone is registered to the bot; ref pull request skip_polling #14

**Comment by Logimann** [comment]
@fabgui Thanks fabgui, it's been running on my docker container like a charm for 2 months ❤️ 

It would be great if this is integrated in the master.

I appreciate your work!

**Comment by marklagendijk** [comment]
I just implemented and released this feature.
