### ISSUE TITLE
Launch of "toogoodtogo-watcher watch"

### ISSUE THREAD

**Issue by sbx59** [marklagendijk/node-toogoodtogo-watcher#98]
Hello,

Sorry, but I am not familiar with Linux.

I want to automatically launch the command: "toogoodtogo-watcher watch" when launching my Raspberry.

Can you help me find the order?

thanks in advance.

**Comment by VeslavG** [comment]
i guess some variation of cron, since Raspberry, per my knowledge runs some stripped down version of debian.
Please check your options here (cron and others):
https://www.simplified.guide/linux/automatically-run-program-on-startup

**Comment by marklagendijk** [comment]
This is a very general question (how to run things on startup on a Raspberry Pi). You're better off asking it somewhere else.
